### ISSUE TITLE
Refactor text formatting for readability

### ISSUE THREAD

**Issue by dasha-korotkykh** [alex-bezpalko/homepage#15]
Hey @alex-bezpalko! 
I loved your work on that page (the fact that it is a tribute to Lio actually made me star your repository), could I offer you some help with formatting the content so it doesn't seem so long and your readers could navigate between the blocks easier?

I would suggest using foldable lists, unordered for left column and ordered for "top 10 facts" list, changing places vision and main info (if this is not a wikipedia article you want to start it with something inspiring), also take the record numbers from main info and present it as, yes, another list, I guess — it is not quite emphasized as an inline text.

Maybe I will cover a few things with pull requests, you can review them and accept if you like or decline if you don't, adecuada?

**Comment by alex-bezpalko** [comment]
Hi @dasha-korotkykh!
Thanks you for being interested in my project. It would be great if you helped me with formatting content. So, I will waiting for you pull request.
