### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by alex-bezpalko** [alex-bezpalko/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by alex-bezpalko** [comment]
Lionel Messi
- https://messi.com/
- https://twitter.com/TeamMessi
- https://www.facebook.com/leomessi/
- https://www.instagram.com/leomessi/

**Comment by volodymyr-kushnir** [comment]
**Мессі?!?!** https://media.giphy.com/media/XqkeNGrs2LM1q/giphy.gif OMG, так, давай Мессі!

**Comment by alex-bezpalko** [comment]
Done
