### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by alex-bezpalko** [alex-bezpalko/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by alex-bezpalko** [comment]
**Club career**
Barcelona
- 2018–now
Barcelona captain
-2017–2018
Domestic double and a record fifth Golden Boot
2016–2017
Fourth Golden Boot
2015–2016
Domestic success
2014–2015
A historic treble
2013–2014
Messidependencia
2012
A record-breaking year
2009–2011
Sustained success
2005–2008
Making the starting eleven
2003–2005
Rise to the first team

**International career**
2018
World Cup
2016
Copa América Centenario, retirement, and return
2014–2015
World Cup and Copa América finals
2011–2013
Assuming the captaincy
2008–2011
Collective decline
2007–2008
Copa América final and Olympic gold
2005–2006
Senior and World Cup debuts
2004–2005
Success at youth level

**Biography**
2019
Scored 600 goals for Barca.
2016
Messi comes out of international retirement to help his team qualify for the world cup.
2014
Scores a hat-trick ( three goals during a single game ), to become FC Barcelona's all-time leading scorer with 371 goals for Barca, beating the record set by Paulino Alcantara, who scored 369 goals.
Wins the Golden Ball award for the best player in the 2014 FIFA World Cup.
Becomes the leading goalscorer in the European Champions League with 74 goals in 91 appearances.
2013
Wins his fourth consecutive record- breaking Ballon D'or ( Golden Ball award ).
2011-2012
Sets the all-time record for the most goals scored in a single season for a major European football league, with 73 goals.
2012
Wins his third Ballon D'or ( Golden Ball award ).
Has a baby boy, Thiago Messi and becomes a father.
2011
Wins his second Ballon D'or ( Golden Ball award).
2010
Wins his first Ballon D'or ( Golden Ball award ).
2009
Wins FIFA World player of the year.
2008
Gets married to childhood friend and girlfriend, Antonella Roccuzzo.
2007
Establishes 'Leo Messi Foundation', working to improve access education and health care for children.
2005
At the age of 18, scored his first official goal and was the youngest player to score for FC Barcelona.
2004
Made his official debut against RCD Espanyol.
2003
Made his unofficial debut for FC Barcelona in a friendly match against FC Porto.
2000
Signs with legendary team FC Barcelona and works his way up through Barca's youth squads.
1998
At the age of 11, he was diagnosed with a growth hormone deficiency.
1995
Joined to play for the local team, Newell's Old boys in Rosario.
1991 
At the age of 4 joined the local club Grandoli where his dad coached him. 
1987
Was born on June 24,1987 , in Rosario, Argentina.

**TITLES WON**

2005
La Liga (FC Barcelona)
Supercopa de España (FC Barcelona)
FIFA U-20 World Cup (Argentina)
2006
La Liga (FC Barcelona)
UEFA Champions League (FC Barcelona)
Supercopa de España (FC Barcelona)
2008
Olympic Gold Medal (Argentina)
2009
La Liga (FC Barcelona)
Copa del Rey (FC Barcelona)
Supercopa de España (FC Barcelona)
UEFA Champions League (FC Barcelona)
UEFA Super Cup (FC Barcelona)
FIFA Club World Cup (FC Barcelona)
2010
La Liga (FC Barcelona)
Supercopa de España (FC Barcelona)
2011
La Liga (FC Barcelona)
Supercopa de España (FC Barcelona)
UEFA Champions League (FC Barcelona)
UEFA Super Cup (FC Barcelona)
FIFA Club World Cup (FC Barcelona)
2012
Copa del Rey (FC Barcelona)
2013
La Liga (FC Barcelona)
Supercopa de España (FC Barcelona)
2015
La Liga (FC Barcelona)
Copa del Rey (FC Barcelona)
UEFA Champions League (FC Barcelona)
UEFA Super Cup (FC Barcelona)
FIFA Club World Cup (FC Barcelona)
2016
La Liga (FC Barcelona)
Copa del Rey (FC Barcelona)
Supercopa de España (FC Barcelona)
2017
Copa del Rey (FC Barcelona)
2018
La Liga (FC Barcelona)
Copa del Rey (FC Barcelona)
2019
La Liga (FC Barcelona)

**Comment by volodymyr-kushnir** [comment]
🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by alex-bezpalko** [comment]
Done
