### ISSUE TITLE
Зробити Ліонелю аватар

### ISSUE THREAD

**Issue by volodymyr-kushnir** [alex-bezpalko/homepage#8]
Треба ж зробити Ліонелю аватар, раз така справа 🤭😁.

**Comment by volodymyr-kushnir** [comment]
Ось заархівований SVG → [lionel-messi.svg.zip](https://github.com/alex-bezpalko/homepage/files/3169535/lionel-messi.svg.zip). Зверни увагу, всередині, на рядку 6 — 
```
<circle id="circle" fill="saddlebrown" r="49.55" cx="49.55" cy="77.85" opacity="0.5" />
```
— можна поставити свій колір в атрибут `fill`. Я б ставив під колір "рамки" самої сторінки, але так, щоб воно разом з тим добре поєднувалося з самим обличчям Мессі. Тому я рекомендую щось з коричневих пастельних тонів: brown, saddlebrown, peachpuff, тощо:
<img width="257" alt="image" src="https://user-images.githubusercontent.com/10290626/57575975-fb612280-7455-11e9-97a9-58d9d9b21892.png">
Але використовуй саме SVG, а не оцю картинку, яку я прикріпив як прев'ю. Оригінал картинки на всякий випадок тут → https://www.gannett-cdn.com/media/2018/03/20/USATODAY/USATODAY/636571401136203077-504503.jpg?width=2560 (там бекграунд теж непоганий, голубенький такий, можна використовувати, лише рамку таку ж саму зробити а-а-а-а-а-або забрати її геть, а натомість бекграунд самого сайту (не резюме, а сайту) зробити голубеньким).

**Comment by volodymyr-kushnir** [comment]
@alex-bezpalko як прочитаєш issue, то закривай одразу, адже аватар вже зроблено, тому... ось.

**Comment by alex-bezpalko** [comment]
Супер, дякую ;)
